/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crearlibro;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Sofía
 */
public class CrearLibro extends javax.swing.JFrame {

    /**
     * Creates new form CrearLibro
     */
    Libro libro = new Libro();
    Autor autor = new Autor();
    DefaultComboBoxModel listaFillAutores = new DefaultComboBoxModel();
    public CrearLibro() {
        
        initComponents();
        jComboBox_AUTOR.setModel(llenarComboAutores());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXT_ISBN = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        jComboBox_AUTOR = new javax.swing.JComboBox<>();
        BTN_NUEVO_AUTOR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TXTSinopsis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton_TERROR = new javax.swing.JRadioButton();
        jRadioButton_CFiccion = new javax.swing.JRadioButton();
        jRadioButton_Romance = new javax.swing.JRadioButton();
        jRadioButton_FANTASIA = new javax.swing.JRadioButton();
        jCheckBox1_LEIDO = new javax.swing.JCheckBox();
        jCheckBox2_LOTENGO = new javax.swing.JCheckBox();
        BTN_GUARDAR = new javax.swing.JButton();
        BTN_CANCELAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ISBN:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Autor:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Título:");

        TXT_ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_ISBNActionPerformed(evt);
            }
        });

        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });

        jComboBox_AUTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_AUTORActionPerformed(evt);
            }
        });

        BTN_NUEVO_AUTOR.setText("Nuevo Autor");
        BTN_NUEVO_AUTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NUEVO_AUTORActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Sinopsis:");

        TXTSinopsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTSinopsisActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Género:");

        jRadioButton_TERROR.setText("Terror");
        jRadioButton_TERROR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_TERRORActionPerformed(evt);
            }
        });

        jRadioButton_CFiccion.setText("Ciencia Ficción");
        jRadioButton_CFiccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_CFiccionActionPerformed(evt);
            }
        });

        jRadioButton_Romance.setText("Romance");
        jRadioButton_Romance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_RomanceActionPerformed(evt);
            }
        });

        jRadioButton_FANTASIA.setText("Fantasía");
        jRadioButton_FANTASIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FANTASIAActionPerformed(evt);
            }
        });

        jCheckBox1_LEIDO.setText("Leido");
        jCheckBox1_LEIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_LEIDOActionPerformed(evt);
            }
        });

        jCheckBox2_LOTENGO.setText("Lo tengo");
        jCheckBox2_LOTENGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2_LOTENGOActionPerformed(evt);
            }
        });

        BTN_GUARDAR.setText("GUARDAR");
        BTN_GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GUARDARActionPerformed(evt);
            }
        });

        BTN_CANCELAR.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_NUEVO_AUTOR)
                            .addComponent(txt_titulo)
                            .addComponent(jComboBox_AUTOR, 0, 359, Short.MAX_VALUE)
                            .addComponent(TXT_ISBN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXTSinopsis)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1_LEIDO)
                            .addComponent(jRadioButton_TERROR)
                            .addComponent(jRadioButton_Romance))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton_FANTASIA)
                                    .addComponent(jRadioButton_CFiccion)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jCheckBox2_LOTENGO)))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_GUARDAR)
                .addGap(45, 45, 45)
                .addComponent(BTN_CANCELAR)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXT_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_AUTOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BTN_NUEVO_AUTOR)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TXTSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton_TERROR)
                    .addComponent(jRadioButton_CFiccion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Romance)
                    .addComponent(jRadioButton_FANTASIA))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1_LEIDO)
                    .addComponent(jCheckBox2_LOTENGO))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_GUARDAR)
                    .addComponent(BTN_CANCELAR))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_ISBNActionPerformed

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloActionPerformed

    private void jRadioButton_TERRORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_TERRORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_TERRORActionPerformed

    private void BTN_NUEVO_AUTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NUEVO_AUTORActionPerformed
        // TODO add your handling code here:
        RegistraAutor rAutor = new RegistraAutor();
        rAutor.setVisible(true);
    }//GEN-LAST:event_BTN_NUEVO_AUTORActionPerformed

    private void BTN_GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GUARDARActionPerformed
        // TODO add your handling code here:
        String ISBN =TXT_ISBN.getText();
        String Titulo=txt_titulo.getText();
        
        String n = jComboBox_AUTOR.getSelectedItem().toString();
        
        String Sinopsis = TXTSinopsis.getText();
        String Genero="";
        if (jRadioButton_TERROR.isSelected()) {
           Genero ="Terror";
        } else if (jRadioButton_CFiccion.isSelected()) {
            Genero ="Ciencia  Ficción";
        } else if (jRadioButton_Romance.isSelected()) {
            Genero ="Romance";
        
        } else if (jRadioButton_FANTASIA.isSelected()) {
            Genero ="Fantasía";
        }
        
        boolean leido;
        boolean lotengo;
        
        if(jCheckBox1_LEIDO.isSelected()){
            leido = true;
        }else{
            leido = false;
        }
        if(jCheckBox2_LOTENGO.isSelected()){
            lotengo = true;
        }else{
            lotengo=false;
        }
        
        libro.setISBN(ISBN);
        libro.setTitulo(Titulo);
        libro.setAutor(n);
        libro.setSinopsis(Sinopsis);
        libro.setGenero(Genero);
        libro.setLeido(leido);
        libro.setLoTengo(lotengo);
        libro.guardarArchivo(libro);
        
       
    }//GEN-LAST:event_BTN_GUARDARActionPerformed

    private void jComboBox_AUTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AUTORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_AUTORActionPerformed

    private void TXTSinopsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTSinopsisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTSinopsisActionPerformed

    private void jRadioButton_CFiccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_CFiccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_CFiccionActionPerformed

    private void jRadioButton_RomanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_RomanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_RomanceActionPerformed

    private void jRadioButton_FANTASIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_FANTASIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_FANTASIAActionPerformed

    private void jCheckBox1_LEIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_LEIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1_LEIDOActionPerformed

    private void jCheckBox2_LOTENGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2_LOTENGOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2_LOTENGOActionPerformed
    
    
    
    private DefaultComboBoxModel llenarComboAutores(){
        
        List<String> fileLineList = new ArrayList<>();
        
        try{
            FileReader fr = new FileReader("./src/crearlibro/Autor.txt");
            BufferedReader br = new BufferedReader(fr);
         
            String d;
            while((d=br.readLine())!= null){
                    fileLineList.add(d);
            }
            br.close();
            
            
            for(int i=0; i < fileLineList.size(); i++){
                boolean duplicado = false;
                String line = fileLineList.get(i);
                String[] parts = new String[0];
                parts = line.split(",");
                
                String part1 = parts[0];
                
                
                /*if(listaFillAutores.isEmpty()){
                listaCursoPorCod.addElement(part1);
                } 
                else{
                for( int j=0; j < listaCursoPorCod.size(); j++){
                    if(Objects.equals(part1, listaCursoPorCod.getElementAt(j))){
                        duplicado = true;
                        break;
                    }
                }
                    if(!duplicado){
                    listaCursoPorCod.addElement(part1);
                    }
                }*/
            }
            
            for (int i = 0; i < fileLineList.size(); i++) {
                listaFillAutores.addElement(fileLineList.get(i));
                System.out.println("Autor txt " + fileLineList.get(i));
                System.out.println("Autor: " + listaFillAutores.getElementAt(i));
            }
            
            
            }catch(Exception e){
            e.printStackTrace();
        }
        return listaFillAutores;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_CANCELAR;
    private javax.swing.JButton BTN_GUARDAR;
    private javax.swing.JButton BTN_NUEVO_AUTOR;
    private javax.swing.JTextField TXTSinopsis;
    private javax.swing.JTextField TXT_ISBN;
    private javax.swing.JCheckBox jCheckBox1_LEIDO;
    private javax.swing.JCheckBox jCheckBox2_LOTENGO;
    private javax.swing.JComboBox<String> jComboBox_AUTOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton_CFiccion;
    private javax.swing.JRadioButton jRadioButton_FANTASIA;
    private javax.swing.JRadioButton jRadioButton_Romance;
    private javax.swing.JRadioButton jRadioButton_TERROR;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
